[font]
size = 18.0

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[window]
opacity = 0.75
